language: erlang
notifications:
  email: false
otp_release:
  - R16B03
  - 17.0
  - 17.1
  - 17.3
  - 17.4
  - 17.5
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19.0
before_script:
  - epmd -daemon
sudo: false
