language: erlang
notifications:
  email: false
otp_release:
  - 21.2
  - 22.0
  - 22.1
  - 22.1.8
  - 22.3
  - 23.0
  - 23.1.2
  - 23.2.5
  - 23.3.1
  - 24.0
  - 24.0.1
  - 24.0.2
  - 24.1
  - 24.2
before_script:
  - epmd -daemon
sudo: false
